sudo: required
dist: trusty
language: c
sudo: false

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install -y bmake

script:
  - bmake -r
  - SID=echo bmake -r test # no need to install SID just for make test
  - bmake -r install

